name: Pull request workflow

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11


      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
          key: gradle-cache-key

      - name: Run Android checks
        run: ./gradlew :app:check --stacktrace

      - name: Upload reports
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Reports
          path: '**/build/reports/*'
          retention-days: 2


      - uses: warting/download-artifact@v3
        if: failure()
        with:
          name: Reports

      - name: Display structure of downloaded files
        if: failure()
        run: ls -R