name: Pull request workflow

on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: Upload reports
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: '**/build/reports/*'
          retention-days: 2


      - name: Run Android checks
        run: rm -Rf app/*


      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
